apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
  namespace: n8n
spec:
  secretName: n8n-tls-secret
  issuerRef:
    name: vault-issuer
    kind: Issuer
  commonName: "*.diagon.ally"
  dnsNames:
  - n8n.diagon.ally
  - "*.diagon.ally"