apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: 
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n
  name: n8n-ingress
  namespace: n8n
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: n8n-letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  
    nginx.ingress.kubernetes.io/rewrite-target: /
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/n8n"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <n8n_external_url>
    secretName: n8n-cert
  rules:
  - host: <n8n_external_url>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-external  # Matches Service name above
            port:
              number: 5678      # Matches Service port
