apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: 
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n
  name: n8n-ingress
  namespace: n8n
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/n8n"
    cert-manager.io/issuer: n8n-letsencrypt
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "n8n-external"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      map $http_upgrade $connection_upgrade {
        default upgrade;
        "" close;
      }
    nginx.ingress.kubernetes.io/configuration-snippet: |
      chunked_transfer_encoding off;
      proxy_http_version 1.1;
      proxy_cache_bypass $http_upgrade;
      proxy_ssl_server_name on;

      proxy_set_header Host $host;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header Cookie $http_cookie;  
      proxy_buffering off;
      proxy_cache off;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <n8n_external_url>
    secretName: n8n-cert
  rules:
  - host: <n8n_external_url>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-external  # Matches Service name above
            port:
              number: 5678      # Matches Service port
