apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-n8n-pv
  annotations:
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/n8n"
spec:
  capacity:
    storage: 50Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany  # NFS supports multiple pods reading/writing
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "<n8n_internal_url>"
    path: /mnt/MainPool/k8s-storage/n8n  # Your NFS export path