apiVersion: v1
kind: Service
metadata:
  name: n8n-internal
  namespace: n8n
spec:
  type: LoadBalancer
  selector:
    service: n8n
  ports:
  - port: 443
    targetPort: 5678
    protocol: TCP
    name: https