apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80 #Container port
  - port: 443
    targetPort: 443
    protocol: TCP     