apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n-external  # Match Ingress backend name
  namespace: n8n
spec:
  type: ClusterIP
  selector:
    app: n8n  # Must match your Deployment's labels
  ports:
  - port: 5678        # Changed from 443
    targetPort: 5678  # Must match containerPort
    protocol: TCP